//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlenderBender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ΡΟΔΟΣ")]
        public string _storeArea {
            get {
                return ((string)(this["_storeArea"]));
            }
            set {
                this["_storeArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string _storeNumber {
            get {
                return ((string)(this["_storeNumber"]));
            }
            set {
                this["_storeNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ΚΩΝΣΤΑΝΤΙΝΟΥ ΥΔΡΑΙΟΥ 71, ΤΚ 85133, ΡΟΔΟΣ")]
        public string _storeAddress {
            get {
                return ((string)(this["_storeAddress"]));
            }
            set {
                this["_storeAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string User {
            get {
                return ((string)(this["User"]));
            }
            set {
                this["User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Στη διάθεσή σας για οποιαδήποτε διευκρίνιση.%0D%0AΣας ευχαριστώ.%0D%0AΜε εκτίμηση" +
            ",%0D%0A%0D%0AΑλέξανδρος Πατσούρος%0D%0AΚατάστημα Ελληνικού%0D%0AE-SHOP.GR%0D%0AΤ" +
            ":2115000500 | Ε:elliniko@e-shop.gr | Ι:www.eshop.gr%0D%0A")]
        public string Signature {
            get {
                return ((string)(this["Signature"]));
            }
            set {
                this["Signature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string monitorfolder {
            get {
                return ((string)(this["monitorfolder"]));
            }
            set {
                this["monitorfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool filemonitor {
            get {
                return ((bool)(this["filemonitor"]));
            }
            set {
                this["filemonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string admVersion {
            get {
                return ((string)(this["admVersion"]));
            }
            set {
                this["admVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PistoMsg {
            get {
                return ((bool)(this["PistoMsg"]));
            }
            set {
                this["PistoMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool windowsWeirdness {
            get {
                return ((bool)(this["windowsWeirdness"]));
            }
            set {
                this["windowsWeirdness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<string> KnownUsers {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["KnownUsers"]));
            }
            set {
                this["KnownUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BreakFree {
            get {
                return ((bool)(this["BreakFree"]));
            }
            set {
                this["BreakFree"] = value;
            }
        }
    }
}
